import {
  Search,
  Bell,
  Sun,
  Moon,
  LayoutGrid,
  MoreHorizontal,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  Check,
  X,
  Plus,
  Pencil,
  Trash2,
  Download,
  Upload,
  Filter,
  RefreshCw,
  Save,
  Copy,
  ExternalLink,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Paperclip,
  Calendar,
  Clock,
  AlertCircle,
  AlertTriangle,
  Info,
  CheckCircle2,
  XCircle,
  Mail,
  MessageSquare,
  Users,
  User,
  UserPlus,
  Folder,
  FolderOpen,
  File,
  FileText,
  FilePlus,
  Settings,
  Home,
  LogOut,
  LogIn,
  Menu,
  Share2,
  Star,
  Tag,
  MapPin,
  Phone,
  Building2,
  Briefcase,
  DollarSign,
  TrendingUp,
  TrendingDown,
  BarChart3,
  PieChart,
  Activity,
  Zap,
  Shield,
  ShieldCheck,
  Key,
  History,
  ListFilter,
  GripVertical,
  KeyRound,
} from "lucide-react";
import type { LucideProps } from "lucide-react";
import { createElement, forwardRef } from "react";
import type { ForwardRefExoticComponent, RefAttributes } from "react";

export const ICON_DEFAULT_STROKE = 1.75;
export const ICON_DEFAULT_SIZE = 16;

type LucideIcon = ForwardRefExoticComponent<
  Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>
>;

const wrap = (Inner: LucideIcon, name: string): LucideIcon => {
  const Wrapped = forwardRef<SVGSVGElement, LucideProps>((props, ref) =>
    createElement(Inner, {
      strokeWidth: ICON_DEFAULT_STROKE,
      size: ICON_DEFAULT_SIZE,
      ...props,
      ref,
    }),
  );
  Wrapped.displayName = `Icon.${name}`;
  return Wrapped as unknown as LucideIcon;
};

export const Icon = {
  Search: wrap(Search, "Search"),
  Bell: wrap(Bell, "Bell"),
  Sun: wrap(Sun, "Sun"),
  Moon: wrap(Moon, "Moon"),
  AppGrid: wrap(LayoutGrid, "AppGrid"),
  More: wrap(MoreHorizontal, "More"),
  ChevronRight: wrap(ChevronRight, "ChevronRight"),
  ChevronLeft: wrap(ChevronLeft, "ChevronLeft"),
  ChevronDown: wrap(ChevronDown, "ChevronDown"),
  ChevronUp: wrap(ChevronUp, "ChevronUp"),
  Check: wrap(Check, "Check"),
  Close: wrap(X, "Close"),
  Plus: wrap(Plus, "Plus"),
  Edit: wrap(Pencil, "Edit"),
  Delete: wrap(Trash2, "Delete"),
  Download: wrap(Download, "Download"),
  Upload: wrap(Upload, "Upload"),
  Filter: wrap(Filter, "Filter"),
  Refresh: wrap(RefreshCw, "Refresh"),
  Save: wrap(Save, "Save"),
  Copy: wrap(Copy, "Copy"),
  ExternalLink: wrap(ExternalLink, "ExternalLink"),
  ArrowRight: wrap(ArrowRight, "ArrowRight"),
  ArrowLeft: wrap(ArrowLeft, "ArrowLeft"),
  ArrowUp: wrap(ArrowUp, "ArrowUp"),
  ArrowDown: wrap(ArrowDown, "ArrowDown"),
  View: wrap(Eye, "View"),
  ViewOff: wrap(EyeOff, "ViewOff"),
  Lock: wrap(Lock, "Lock"),
  Unlock: wrap(Unlock, "Unlock"),
  Attachment: wrap(Paperclip, "Attachment"),
  Calendar: wrap(Calendar, "Calendar"),
  Clock: wrap(Clock, "Clock"),
  Alert: wrap(AlertCircle, "Alert"),
  Warning: wrap(AlertTriangle, "Warning"),
  Info: wrap(Info, "Info"),
  Success: wrap(CheckCircle2, "Success"),
  Error: wrap(XCircle, "Error"),
  Mail: wrap(Mail, "Mail"),
  Comment: wrap(MessageSquare, "Comment"),
  Users: wrap(Users, "Users"),
  User: wrap(User, "User"),
  UserAdd: wrap(UserPlus, "UserAdd"),
  Folder: wrap(Folder, "Folder"),
  FolderOpen: wrap(FolderOpen, "FolderOpen"),
  File: wrap(File, "File"),
  FileText: wrap(FileText, "FileText"),
  FileAdd: wrap(FilePlus, "FileAdd"),
  Settings: wrap(Settings, "Settings"),
  Home: wrap(Home, "Home"),
  SignOut: wrap(LogOut, "SignOut"),
  SignIn: wrap(LogIn, "SignIn"),
  Menu: wrap(Menu, "Menu"),
  Share: wrap(Share2, "Share"),
  Star: wrap(Star, "Star"),
  Tag: wrap(Tag, "Tag"),
  Location: wrap(MapPin, "Location"),
  Phone: wrap(Phone, "Phone"),
  Building: wrap(Building2, "Building"),
  Briefcase: wrap(Briefcase, "Briefcase"),
  Money: wrap(DollarSign, "Money"),
  TrendUp: wrap(TrendingUp, "TrendUp"),
  TrendDown: wrap(TrendingDown, "TrendDown"),
  BarChart: wrap(BarChart3, "BarChart"),
  PieChart: wrap(PieChart, "PieChart"),
  Activity: wrap(Activity, "Activity"),
  Zap: wrap(Zap, "Zap"),
  Shield: wrap(Shield, "Shield"),
  ShieldCheck: wrap(ShieldCheck, "ShieldCheck"),
  Key: wrap(Key, "Key"),
  History: wrap(History, "History"),
  ListFilter: wrap(ListFilter, "ListFilter"),
  Drag: wrap(GripVertical, "Drag"),
  Totp: wrap(KeyRound, "Totp"),
} as const;

export type IconName = keyof typeof Icon;
